# Generated by Django 5.2.4 on 2025-11-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultymember',
            name='department',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='phone',
        ),
        migrations.AddField(
            model_name='facultymember',
            name='contact_no',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='designation',
            field=models.CharField(default='Professor', max_length=50),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='experience',
            field=models.CharField(default='0 years', max_length=20),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='qualifications',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='specialization',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
